<a href="https://colab.research.google.com/github/PearlSikka/language-ninja/blob/master/Understanding_word_embeddings_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
sentences=['I love dogs','I want to have a dog','It would be wonderful to have a dog']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer=Tokenizer(num_words=30,lower=True,split=' ')

In [ ]:
sequences=tokenizer.fit_on_texts(sentences)

In [ ]:
tokenizer.word_index

{'a': 4,
 'be': 11,
 'dog': 5,
 'dogs': 7,
 'have': 3,
 'i': 1,
 'it': 9,
 'love': 6,
 'to': 2,
 'want': 8,
 'wonderful': 12,
 'would': 10}

In [ ]:
seq=tokenizer.texts_to_sequences(sentences)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
padded=pad_sequences(seq)

In [ ]:
print(padded)

[[ 0  0  0  0  0  1  6  7]
 [ 0  0  1  8  2  3  4  5]
 [ 9 10 11 12  2  3  4  5]]


In [ ]:
print(padded.shape[1])

8


In [ ]:
from tensorflow.keras.layers import Embedding,Dense,Flatten

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
model=Sequential()

In [ ]:
embedding_layer=model.add(Embedding(input_dim=30,output_dim=4,input_length=padded.shape[1]))

In [ ]:
model.output_shape

(None, 8, 4)

In [ ]:
word_vec=model.add(Flatten(embedding_layer))

In [ ]:
model.output_shape

(None, 32)

In [ ]:
import keras

In [ ]:
model.compile(optimizer=keras.optimizers.Adam(lr=1e-3),loss='binary_crossentropy',metrics=['acc'])

In [ ]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 8, 4)              120       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
Total params: 120
Trainable params: 120
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
embeddings=model.predict(padded)

In [ ]:
embeddings.shape

(3, 32)

In [ ]:
print(embeddings)

[[-0.01872849 -0.04797459  0.03956915 -0.04462173 -0.01872849 -0.04797459
   0.03956915 -0.04462173 -0.01872849 -0.04797459  0.03956915 -0.04462173
  -0.01872849 -0.04797459  0.03956915 -0.04462173 -0.01872849 -0.04797459
   0.03956915 -0.04462173 -0.0058645   0.02711881  0.00265054 -0.01248588
   0.02194018  0.00160649  0.011636    0.03894926  0.02013302  0.04051527
   0.01802767  0.04468035]
 [-0.01872849 -0.04797459  0.03956915 -0.04462173 -0.01872849 -0.04797459
   0.03956915 -0.04462173 -0.0058645   0.02711881  0.00265054 -0.01248588
  -0.03646675  0.01246463 -0.02161659  0.03325936 -0.03654734 -0.03333615
  -0.02868624 -0.02305799 -0.00400965 -0.04017516 -0.04059831 -0.03638431
   0.02336622  0.02416473  0.0246908   0.01249458 -0.04469686 -0.04553995
   0.01142102  0.03626997]
 [ 0.02696354 -0.01354486 -0.00957673  0.01774893  0.04993579  0.0337227
   0.02782904  0.01144833  0.03969407  0.04271953 -0.02954074 -0.01688446
   0.00142474 -0.04509921  0.00543742 -0.02269064 -0.036547

In [ ]:
embed_re=embeddings.reshape(-1,8,4)

In [ ]:
embed_re.shape

(3, 8, 4)

In [ ]:
embed_re

array([[[-0.01872849, -0.04797459,  0.03956915, -0.04462173],
        [-0.01872849, -0.04797459,  0.03956915, -0.04462173],
        [-0.01872849, -0.04797459,  0.03956915, -0.04462173],
        [-0.01872849, -0.04797459,  0.03956915, -0.04462173],
        [-0.01872849, -0.04797459,  0.03956915, -0.04462173],
        [-0.0058645 ,  0.02711881,  0.00265054, -0.01248588],
        [ 0.02194018,  0.00160649,  0.011636  ,  0.03894926],
        [ 0.02013302,  0.04051527,  0.01802767,  0.04468035]],

       [[-0.01872849, -0.04797459,  0.03956915, -0.04462173],
        [-0.01872849, -0.04797459,  0.03956915, -0.04462173],
        [-0.0058645 ,  0.02711881,  0.00265054, -0.01248588],
        [-0.03646675,  0.01246463, -0.02161659,  0.03325936],
        [-0.03654734, -0.03333615, -0.02868624, -0.02305799],
        [-0.00400965, -0.04017516, -0.04059831, -0.03638431],
        [ 0.02336622,  0.02416473,  0.0246908 ,  0.01249458],
        [-0.04469686, -0.04553995,  0.01142102,  0.03626997]],

    